### ISSUE TITLE
changing month hides the top menu on Givers page

### ISSUE THREAD

**Issue by Tuhaj** [Appnroll/kudosapp-frontend#24]

**Comment by mateuszkocz** [comment]
It doesn't.

![2019-01-28 08-15-36 2019-01-28 08_16_27](https://user-images.githubusercontent.com/1478684/51820133-19ef4380-22d5-11e9-92c8-41344c4cd44f.gif)

**Comment by mateuszkocz** [comment]
Fixed in #31
