### ISSUE TITLE
Opening app through "authorized-required" URL does not render Login Page

### ISSUE THREAD

**Issue by kgajowy** [Appnroll/kudosapp-frontend#40]
`https://appnroll.github.io/kudosapp-frontend/#/stats` it redirects to `/login` but does not show a thing - even the nav bar.
Possibly duplicate of #34 
![image](https://user-images.githubusercontent.com/3466388/52559950-23a99880-2df7-11e9-8c7b-3a9dcf522958.png)

**Comment by mateuszkocz** [comment]
All paths that require authentication should redirect to `/`. `/login` is a mistake. I initially thought this will be the place to add credentials.
