### ISSUE TITLE
Missing February entries

### ISSUE THREAD

**Issue by kgajowy** [Appnroll/kudosapp-frontend#48]
Newest one: 31.01
![image](https://user-images.githubusercontent.com/3466388/52560497-da5a4880-2df8-11e9-9815-479a2acc55b1.png)

Givers:
![image](https://user-images.githubusercontent.com/3466388/52560513-e514dd80-2df8-11e9-9803-1b3c88a379a9.png)

**Comment by Tuhaj** [comment]
@dotadota will do the import

**Comment by dotadota** [comment]
That is fixed already.
